### PR TITLE
Build options in multiple stages in template listbox helper

### LINKED ISSUE #109: Build options in multiple stages in template listbox helper
If a listbox is created out of thousands of entities they are all fetched at the same time resulting in memory limit errors.

Instead, fetch results 100 by 100 and gradually build the options array.

Note: this removes the 'unique' property of the listbox helper which made duplicate values appear only once in listboxes. However this was not a particularly helpful option since it could be problematic when you have more than one entity using the same title.

See joomlatools/joomlatools-framework#17

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #109

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@johanjanssens All yours to review and merge

**Comment by johanjanssens** [comment]
@ercanozkaya  This is looking good. 

Thoughts, I wonder if we can make this work out of the box, fetch, could query the database per 100 items, and re-fetch when buffer is empty. 

In PHP 5.5+ you could use generators for this, in early versions we could build a special iterator for this?

**Comment by ercanozkaya** [comment]
@johanjanssens I like the generator idea, not sure if it can be done automatically with fetch() but we can have a model generator maybe?

**Comment by johanjanssens** [comment]
@ercanozkaya We could, I'll make note of this, can we already merge these changes to Kodekit?

**Pull request merged**
