### PR TITLE
Merge Feature/169-sync

### LINKED ISSUE #169: Synchronize with Joomlatools Framework
Bring changes from the develop branch of Joomlatools Framework 

See: https://github.com/joomlatools/joomlatools-framework/issues?q=is%3Aopen+is%3Aissue+milestone%3ADevelop
See: https://github.com/joomlatools/joomlatools-framework/issues/190
https://github.com/joomlatools/joomlatools-framework/issues/181
https://github.com/joomlatools/joomlatools-framework/issues/212
https://github.com/joomlatools/joomlatools-framework/issues/220
https://github.com/joomlatools/joomlatools-framework/issues/224
https://github.com/joomlatools/joomlatools-framework/issues/198
https://github.com/joomlatools/joomlatools-framework/issues/196
https://github.com/joomlatools/joomlatools-framework/issues/36
https://github.com/joomlatools/joomlatools-framework/pull/227
https://github.com/joomlatools/joomlatools-framework/issues/229
https://github.com/joomlatools/joomlatools-framework/issues/232
https://github.com/joomlatools/joomlatools-framework/issues/233

### PR DESCRIPTION
**Pull request by ercanozkaya**
Closes #169

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@johanjanssens I'm ready to merge this in. Most changed files are for the static assets. The first 40 or so is for PHP and the synced tickets are in the issue description. Would you like a review first or shall I merge it?

**Comment by johanjanssens** [comment]
@ercanozkaya Don't have time to review, sorry. Please double check yourself, and coordinate with another developer if needed. 

Can you also make a list of what hasn't been merged? I think we didn't do the template changes? Lets make a separate ticket for that.

**Comment by ercanozkaya** [comment]
@johanjanssens Merged the changes. It's working stable with Foliokit. Only template changes are not synced and made an additional ticket for it.

**Comment by johanjanssens** [comment]
Perfect!

**Pull request merged**
